### ISSUE TITLE
Save/Update/Finish Button hidden by status bar 

### ISSUE THREAD

**Issue by corayana** [LiamMorrow/LiftLog#156]
Hi,
I just started using your app and am pretty happy so far. 
One issue that bothers me is that the app reaches under the status bar on my phone (Google Pixel 4a). This makes it very difficult to save/update or finish a session. I would bei very happy you could fix this.

![Screenshot_20240509-140845](https://github.com/LiamMorrow/LiftLog/assets/44569582/6293ce4c-3308-4dd2-866b-aa6f68fa8a2b)

**Comment by LiamMorrow** [comment]
Thanks for the report! It definitely shouldn't be doing that, I'll see what I can do

**Comment by LiamMorrow** [comment]
Would you be able to tell me your android version please?
You can find it by going into your phone's settings, scrolling to "System" then tapping "About Phone"

Thank you!

**Comment by corayana** [comment]
Thank you for the quick response. My android version is 13.

**Comment by LiamMorrow** [comment]
Fantastic.  I'll have a play with the emulator tonight to see what I can do.

**Comment by LiamMorrow** [comment]
I cannot for the life of me get this bug to show up I'm afraid.  I have a workaround, which would just amount to offsetting the top by a static distance.  I'll release a new version with this toggle which should help you in the meantime.

**Comment by corayana** [comment]
Thank you very much for your efforts! Unfortunately, I have no idea what the problem might be.
Anyway, the workaround works so far, at least for ending a session (but not for creating/editing a new/existing session)

**Comment by LiamMorrow** [comment]
Yeah it's a headscratcher.  You say it doesn't work for creating/editing sessions.  Could you show me a screenshot of what you mean?  It should apply everywhere

**Comment by LiamMorrow** [comment]
Also, do you have developer mode enabled?  If so, would you be able to show your WebView implementation?  I wonder if it's a browser version issue...

**Comment by LiamMorrow** [comment]
https://github.com/LiamMorrow/LiftLog/blob/30b2530d4ec5d1bc321dd7f5c07ab34b1a29411f/LiftLog.Maui/Platforms/Android/MainActivity.cs#L55

This is where I perform the calculation to get the insets.  It works on all emulators and my phone (asus zenfone 9).

**Comment by spar34vi** [comment]
I'm getting the same issue on Pixel 7 pro (android 15)

**Comment by LiamMorrow** [comment]
I've got a clue! Seems like I can reproduce it when using a non english language (thanks for the translation @spar34vi!) I have a feeling I know exactly what it is now... I think that the inset is resolving to a decimal, and I am formatting it for the css using the region's format (i.e. commas).  But CSS is not regionalised, and it REQUIRES periods.

<img width="452" alt="image" src="https://github.com/user-attachments/assets/21262d70-ee1a-49f8-a858-b56ad48a8648" />

A fix for this will be inbound! 🎉  Thanks for all the reports!
