### ISSUE TITLE
No different weight for different sets options ?

### ISSUE THREAD

**Issue by mateo-covacho** [LiamMorrow/LiftLog#228]
Pretty self explanatory:

It'd be nice to be able to have different weights for different sets in a exercise in case the preselected weight turn out to be too much or too little

**Comment by LiamMorrow** [comment]
G'day @mateo-covacho , I need to add a Tip for this, but it is actually already a feature!  Simply press the weight icon in each exercise.


https://github.com/user-attachments/assets/2a6ea498-20ef-4240-b3b2-e0855484d1ea

**Comment by mateo-covacho** [comment]
@LiamMorrow For archives sake the video can't be viewed  or downloaded, and cant seem to figure out how to do it.
