### ISSUE TITLE
tap to reveal  overflown exercise name

### ISSUE THREAD

**Issue by LiamMorrow** [LiamMorrow/LiftLog#241]
Exercise names can overflow and be truncated with an elipsis...  Tapping them should reveal them somehow.  Thinking either tooltip, or potentially scrolling like a music player?

**Comment by cannontrodder** [comment]
My issue with the overflow is it hides the history icon which I find crucial for making decisions on tweaking things!

**Comment by LiamMorrow** [comment]
Thanks for letting me know! It definitely shouldn't be doing that, and I can't reproduce it. 🤔  Are you on iphone or android?

The history button does hide itself when you have never done that exercise before (exact same amount of sets / reps/ exact name).  Is is possible this is the cause of it hiding?  I've been moving to a more loose model, so I think I could start showing it all the time

**Comment by cannontrodder** [comment]
This is almost certainly to because I edited the exercise (added a set)!

**Comment by LiamMorrow** [comment]
That's good to know :) That change to show other anything with the same name in the previous view is now live on Android (having trouble with iOS builds rn)
