### ISSUE TITLE
Superset with more than one exercise

### ISSUE THREAD

**Issue by bschwehn** [LiamMorrow/LiftLog#246]
If you have more than one exercise marked as superset, I would expect that LiftLog selects the first exercise in the current superset set after completing the last one in the superset.
Currently, it will always select the exercise one previously.

For example 4 exercises:
```

| Name | Sets | Superset |
|------+------+----------|
| A    |    2 | Yes      |
| B    |    2 | Yes      |
| C    |    2 | No       |
| D    |    2 | No       |
```

It will currently go A, B, C, B, C, D, D. Instead I think it should go A, B, C, A, B, C, D, D.

This is not a big issue, as you can just manually go the the first exercise.

I tried a fix that also handles a (weird) scenario when you do different number of sets in the superset exercises.

```
| Name | Sets | Superset |
|------+------+----------|
| A    |    4 | Yes      |
| B    |    3 | Yes      |
| C    |    2 | Yes      |
| D    |    3 | No       |
| E    |    2 | No       |
|      |      |          |
```

it should go A, B, C, D, A, B, C, D, A, B, D, A, E

Though this is certainly a weird setup.

I've done this change to SessionModels.NextExercise:

```
    public RecordedExercise? NextExercise
    {
        get
        {
            var latestExerciseIndex = RecordedExercises
                .IndexedTuples()
                .Where(x => x.Item.LastRecordedSet is not null)
                .OrderByDescending(x => x.Item.LastRecordedSet?.Set?.CompletionTime)
                .Select(x => x.Index)
                .FirstOrDefault(-1);

            // If the current exercise is a superset, find the next exercise in the
            // current list of superset exercises that has a set remaining.
            var nextSuperset = -1;

            if (latestExerciseIndex > -1)
            {
                for (var i = latestExerciseIndex; i < RecordedExercises.Count; i++)
                {
                    if (!RecordedExercises[i].Blueprint.SupersetWithNext)
                    {
                        break;
                    }

                    if (
                        i < RecordedExercises.Count - 1
                        && RecordedExercises[i + 1].HasRemainingSets
                    )
                    {
                        nextSuperset = i + 1;
                        break;
                    }
                }

                if (nextSuperset != -1)
                {
                    return RecordedExercises[nextSuperset];
                }

                // If the current exercise is the last of a superset, find the first
                // exercise in the current list of superset exercises that has a set remaining.
                var firstSuperset = -1;

                for (var i = latestExerciseIndex - 1; i >= 0; i--)
                {
                    if (!RecordedExercises[i].Blueprint.SupersetWithNext)
                    {
                        break;
                    }

                    if (RecordedExercises[i].HasRemainingSets)
                    {
                        firstSuperset = i;
                    }
                }

                if (firstSuperset != -1)
                {
                    return RecordedExercises[firstSuperset];
                }
            }

            return RecordedExercises
                .Where(x => x.HasRemainingSets)
                .MaxBy(x => x.LastRecordedSet?.Set?.CompletionTime);
        }
    }

```

and this seems to work ok, but I have not tested it well... Let me know if you'd like me to create a PR.

**Comment by LiamMorrow** [comment]
Oh interesting, that's definitely the behaviour that it used to have.  Must've been a regression

**Comment by LiamMorrow** [comment]
Thanks for finding this! Turns out it wasn't a regression, just something I never got around to.  I wrote some tests for it and patched the behaviour in #248 .  I tried your patch but it failed a couple of the tests, otherwise I would have been super happy to get it in.

It's a super complex function, I'd love to simplify it, maybe with some sort of "GetSupersetChain" function which returns an IEnumerable of exercises going through their superset in the correct order

**Comment by bschwehn** [comment]
Ah, thanks, it's a better fix anyway 👍

**Comment by bschwehn** [comment]
@LiamMorrow this is now crashing unfortunately :)

To repro, try a session with 3+ exercises and mark the second to last as superset, it will crash when trying to do mask the last rep of the last exercise as completed.

One fix could be in line SessionModels.cs:72 to replace

             `      ` indexToJumpBackTo < RecordedExercises.Count``

with 

                 `   indexToJumpBackTo < RecordedExercises.Count - 1`


or in line 79 instead of 

                                      `  return RecordedExercises[indexToJumpBackTo];`

do

               ```
 if (indexToJumpBackTo < RecordedExercises.Count)
                {
                    return RecordedExercises[indexToJumpBackTo];
                }

```
