### ISSUE TITLE
(Feature Request) Delete sessions

### ISSUE THREAD

**Issue by th0mcat** [LiamMorrow/LiftLog#263]
I’ve accidentally added sessions to my calendar.  I do not see a way to delete them in the app.

**Comment by bschwehn** [comment]
You can long tap on the session, at least that works for me.

**Comment by th0mcat** [comment]
Disclaimer: I’m on the iOS 18 Beta.

Here’s a screen recording I took.  I’m able to delete the session by pressing the date, but nothing happens if I long press the session.

https://github.com/user-attachments/assets/c14c5588-7bfe-4392-895f-80db4feccdc8

Also, in the workout tab, my session shows up three times.

**Comment by LiamMorrow** [comment]
Interesting.  The iOS beta has broken a few things in MAUI recently so I don't doubt that it would be something that slipped through the cracks

**Comment by LiamMorrow** [comment]
> Also, in the workout tab, my session shows up three times.

Ah yeah that is expected (if a little strange) if you only have a single day in the plan.  Do you have multiple days setup in your plan?

**Comment by th0mcat** [comment]
I did originally, then I split it into three.  I’ll re-consolidate them
