### ISSUE TITLE
Navigation buttons overlap

### ISSUE THREAD

**Issue by albertodlc** [LiamMorrow/LiftLog#277]
![Screenshot_20240924-100423_LiftLog](https://github.com/user-attachments/assets/5c85e039-265e-4afd-ab73-217b679de533)

On Android 14 last version 2.18.2

**Comment by LiamMorrow** [comment]
Thanks for the report!
I'm unfortunately unable to replicate this no matter what I try.  I've tracked this in https://github.com/LiamMorrow/LiftLog/issues/156

In the meantime, a workaround is to go into settings -> App Configuration -> Status Bar Fix

I'm pushing out an update which will push the bottom up as well.
