### ISSUE TITLE
Previous Sessions in History View always empty

### ISSUE THREAD

**Issue by bschwehn** [LiamMorrow/LiftLog#292]
Opening the "Previous Sessions" view from this history page always says "You've never done this exercise before"

I guess the easiest fix would be to load `previousCompleted` in `HistoryEditPage` just like is done in `SessionPage` or to just hide the button in the history view.

But maybe the expectation here would be to see the previous sessions relative to the datetime of the currently viewed historic session not the latest 10 relative to now?

**Comment by LiamMorrow** [comment]
Hmm yeah good point!  It was originally designed to not show in the historical view (for the main reason is it would be unclear to me what the value is). We got that for free when the button hid itself when there were no exercises, but now it's always present.

If I had found this myself, I would have just hidden the button on the history pages, like how it was prior to this change.  Do you see value for yourself if it showed the ones prior to that date?

**Comment by bschwehn** [comment]
Personally I would maybe see some _minor_ value, but I think this is counteracted by the concern that it might easily be confusing to users. Some may expect that it shows the latest exercises because that is what it does in the session view and others may expect that it shows the previous one with the selected one as anchor because we're in the history view... So I think just hiding the button is a reasonable fix.

Maybe a button that instead goes to the stats page filtered on that exercise could be an addition at some point, but not sure how useful that would be either.
