### ISSUE TITLE
Upcoming Workouts should continue in plan even when interrupted by freeform session

### ISSUE THREAD

**Issue by bschwehn** [LiamMorrow/LiftLog#293]
The Upoming Workouts normally shows the next session according to the selected plan.
But if you do a freeform session, the next time the "Upcoming Workouts" screen restarts the plan from scratch.

E.g. with the default plan, select "Light Calisthenics" as a plan. This plan has 3 sessions: Push, Pull and Legs.
After doing a Push session, "Upcoming Workouts" shows "Pull" as the next session as expected.

But if you now do a "Freeform Session", "Upcoming Workouts" starts again with "Push".
IMO it would be better if it resumed the current plan based on the last exercise that was actually part of the plan and resumes with Pull in this case.

Maybe we can get the latest record matching the current plan [here](https://github.com/LiamMorrow/LiftLog/blob/main/LiftLog.Ui/Services/SessionService.cs#L27) rather than simply the latest here?

Background for me is that I normally use a plan I created but few times a month I do a workout together with a friend which I track as a freeform session. I want to continue with my plan then the next time.

Not a big issue of course, I can just pick the correct session from the list, it's just a minor annoyance.

Edit: thinking some more about it, it is maybe not as clear what the best behaviour is.
For example if you follow a plan A for a few weeks, then switch to plan B for a few weeks, then back to plan A, probably it should restart plan A at the beginning, because a lot of time has passed now. But some users may prefer it to resume plan A where they left of.

Maybe it should only resume the plan if the only sessions in between are all freeform sessions? That would also help for the user that wants to use freeform sessions just to track the bodyweight...

**Comment by LiamMorrow** [comment]
Ah yeah interesting. That does make a bit of sense.  Yeah I think the easiest / simplest which might cover all cases is to just ignore "Freeform" sessions in the upcoming exercise list.
