### ISSUE TITLE
Filtered stats page shows tooltips / weights for wrong exercise

### ISSUE THREAD

**Issue by bschwehn** [LiamMorrow/LiftLog#295]
I have not figured out the exact conditions, maybe it happens when you have similarly named exercises, maybe the similar names are unrelated.

Repro Case:

Create a new plan with 3 exercises:
- Deadlift
- Romanian Deadlift
- Deadlift, Romanian

Do 3 sessions, then go to the history. Filter the history by "Roman". Observe that "Romanian Deadlift" and "Deadlift, Romanian" show in the page as expected. But the "Romanian Deadlift" graph has "Deadlift" as tooltip and the "Deadlift, Romanian" graph has "Romanian Deadlift" as tooltip:
![image](https://github.com/user-attachments/assets/e660c159-2f8b-4ef8-a3cd-47df0c6ff642)

The weights are also wrong, for example here I've 7.5, 22.5 and 2.5kg for the three exercises:

![image](https://github.com/user-attachments/assets/84848c4b-1770-4898-900e-307ecc1a059a)

but when filtered the weights come from the wrong exercise:

![image](https://github.com/user-attachments/assets/0af4c7c0-6fa5-4ae8-9c3a-ed3eb18ff1b8)

**Comment by bschwehn** [comment]
The issue seems to be caused by OnInitializedAsync in StatGraphCardContent not being called after the filtering, I guess the existing component is reused. You can also see that the loading indicator is not showing when filtering.

Moving the RenderDelay invokation of StateHasChanged into OnParametersSetAsync fixes the issue (though without further changes it will cause the rendering being done multiple times), but not sure if this is the correct way to handle it. Not familiar with Fluxor, just hoping this additional info helps...

**Comment by LiamMorrow** [comment]
It does, thank you! I'm fairly sure I just need to set a key on each of the list items so they don't get reused improperly. After doing that I am unable to reproduce 🎉
