### ISSUE TITLE
Proposal: Reference Implementation Using AWS Lambda/S3 to store cloud backups

### ISSUE THREAD

**Issue by cannontrodder** [LiamMorrow/LiftLog#301]
I'm going to build a terraform stack which will deploy the neccessary infrastructure in my person AWS account to host a simple lambda that implements the current remote backup protocol.

I'm more of a node developer so this might be abhorrent to you, although I'm not against the idea of revisiting and doing it in .NET - I'm just super rusty. I will do this with the consideration that a later implementation could be done in .NET and be dropped into the lambda.

My main question is, would you be interested in having this reference in your main repo, and if so, any guidelines on how you want it structured? There'll need to be a folder for some terraform and a folder to store the lambda implementation. For the latter I will be making LiftLog.BackupServer.Lambda.Node

I won't be offended if you don't want it, I'll set it up elsewhere and maybe share the link for your docs?

**Comment by LiamMorrow** [comment]
Hey, that would be great! I have no objection to node. If there is going to be a couple implementations of the backup server, it might be good to just slap them all in an examples dir.  I'll amend the location of the current remote backup reference.

Something like this:
```
/examples/remote-backup/reference-server-implementation/(existingOne)
/examples/remote-backup/aws-lambda-s3-deployable/(src|terraform)
```

Not too fazed on what name you go for though :)  It would be good if when you add it, you update the remote backup docs to mention it (instructions would be a bonus)

**Comment by cannontrodder** [comment]
I'll follow those guidelines and there are docs. I'm just struggling at the moment to integrate with the actual app itself. Can you confirm the format of the web upload or point me to the implementation? I'm getting a payload which is application/x-www-form-urlencoded but it does not look like the typial fomr you might get POSTed to an endpoint, I see the bytes `[Object` at the front so I'm assuming the entire body is just a binary object and that object is a serialized blob of some type?

**Comment by LiamMorrow** [comment]
>  I'm assuming the entire body is just a binary object and that object is a serialized blob of some type?

Yeah that's exactly it.  The entire body is just the backup file's bytes, you can store it exactly as is.  The actual file is just a gzipped protobuf object as defined [here](https://github.com/LiamMorrow/LiftLog/blob/main/LiftLog.Ui/Models/ExportedDataDao/ExportedDataDaoV2.proto)

If you're looking to store backups which the app will understand, just persist the blob exactly as is (don't ungzip it) as a `filename.liflogbackup.gz`.  The app expects that the file is gzipped.

If you want to explore the data, you can ungzip it, then deserialize it with protobuf.  @bschwehn has made a CLI which can convert it to CSV [here](https://github.com/bschwehn/LiftLogExport)

**Comment by cannontrodder** [comment]
Ah - this is good news. I have a feeling I've cracked it but I have to be careful that I'm not allowing API gateway to decode it in any other way other than converting thge octet-stream to a buffer I van send to S3. I've been ungzipping it but the typical unix command expects that to be an archive. If I can inspect a backup copied to ios storage and get compariable results with the S3 download, I'll feel that our data is safe!

**Comment by cannontrodder** [comment]
I've opened a [PR](https://github.com/LiamMorrow/LiftLog/pull/303) - hopefully the instructions are good enough.
