### ISSUE TITLE
Previous Sessions screen shows target reps rather than actual reps when all sets have same #reps

### ISSUE THREAD

**Issue by bschwehn** [LiamMorrow/LiftLog#307]
when all sets have the same reps (lower than the target reps):
![image](https://github.com/user-attachments/assets/bdaa663d-cd9d-4d21-b1cf-a858cc47b43d)

The history shows the target reps instead of the actual reps:
![image](https://github.com/user-attachments/assets/9b0b8143-245c-41b3-a408-3a4bc3205aad)

**Comment by LiamMorrow** [comment]
Oh classic, thank you for finding (and fixing!) this.  I knew that spaghetti was going to bite me someday
