### ISSUE TITLE
In app reporting

### ISSUE THREAD

**Issue by jgonzales20** [LiamMorrow/LiftLog#323]
In app bug / feature request reporting using a form or similar experience.

**Comment by LiamMorrow** [comment]
Great idea! It's been on my roadmap for a while.  I'll have to think about where it would end up.  Ideally I'd like it to end up on github

**Comment by jgonzales20** [comment]
Sign in with GitHub would be optimal, it would just use a template
________________________________

**Comment by LiamMorrow** [comment]
Thanks for the report! I've just merged #328 which will expose two buttons in the settings section for submitting feature requests/bug reports
