### ISSUE TITLE
Search workout

### ISSUE THREAD

**Issue by jgonzales20** [LiamMorrow/LiftLog#336]
**Is your feature request related to a problem? Please describe.**

Add a search icon next to the workout name that just opens the default browser on the phone and queries the workout "title" 

**Describe the solution you'd like**
A easy way in the app to distinguish what workouts look like

**Describe alternatives you've considered**
Using links but external links don't show when using the workout 

**Additional context**
None

**Comment by LiamMorrow** [comment]
Thanks for the suggestion! Recently a change was pushed which surfaces the external link into the workout:
<img width="441" alt="image" src="https://github.com/user-attachments/assets/5a95bf33-861f-4e7e-a35f-d99d24c1bc59">

Would this solve your issue?

**Comment by jgonzales20** [comment]
Just noticed this, works great!
