### ISSUE TITLE
Missing Hollow Hold

### ISSUE THREAD

**Issue by jgonzales20** [LiamMorrow/LiftLog#337]
**Is your feature request related to a problem? Please describe.**
Add a workout type

**Describe the solution you'd like**
Add a workout called Hollow Hold

**Describe alternatives you've considered**
Typing it in 

**Additional context**
None

**Comment by LiamMorrow** [comment]
Thanks! Once you perform an exercise, it will be added to the exercise list.  However if you think it should be in the original list, that can be acheived. It is sourced from:
https://github.com/yuhonas/free-exercise-db

So we'd want to suggest it there!
