### ISSUE TITLE
Feature Request: Body weight tracking and Premade excercises

### ISSUE THREAD

**Issue by Sinasta** [LiamMorrow/LiftLog#72]
I really like your App and i use it quite a lot. I would like to ask you if you plan on implementing features like body weight tracking, premade exercises and the corresponding muscle types? A good inspiration for those kind of features could be [LiftApp](https://github.com/patrykandpatrick/liftapp) 
Thanks A lot for your amazing work!

**Comment by LiamMorrow** [comment]
That's great to hear!

Yeah I definitely have bodyweight tracking planned and up there on my priority list. I was thinking of just adding it as an additional field at the end of a session, would this suit your purposes?
Something like this:
![image](https://github.com/LiamMorrow/LiftLog/assets/13741016/e000dd95-5fde-4fe4-a5d1-1f20e9a96102)


As for a premade list of exercises yeah it's a good idea I'll need to source a list I can use and make an exercise picker.  I wanted to do some sort of autocomplete in the text boxes when selecting an exercise, but the material web library doesn't support it.

**Comment by LiamMorrow** [comment]
https://github.com/LiamMorrow/LiftLog/pull/74

Once this PR is released it should allow you to track your bodyweight

**Comment by LiamMorrow** [comment]
A long time coming, but a list of built in exercises to search from has been provided in this pr: #196 

It's not as refined as showing you what it is working, but it should make typing a lot easier and consistent
